[workspace]
members = ["contract", "dario_fsm", "data_driver", "tests"]
resolver = "2"

[workspace.dependencies]
dusk-core = { version = "1.4.0", default-features = false }
dusk-data-driver = "0.3"
dusk-forge = "0.1.0"
dusk-vm = { version = "1.4.2", default-features = false }
